### ISSUE TITLE
Library should support netstandard, not netcoreapp

### ISSUE THREAD

**Issue by cannorin** [yutopp/VJson#7]
Related: #6
See: https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support

Setting `TargetFrameworks` to `netstandard1.6;net45;net35` is preferred (use `netstandard2.0` instead of `netstandard1.6` if you have some missing APIs in 1.6). This also solves #6, as UWP 10.0 is compatible to netstandard1.x/2.0 .

**Comment by yutopp** [comment]
Thank you for your advice!

It sounds good to make the library more portable, however  I think `netcoreapp1.0/2.0` are still needed for some reasons :sob: (e.g. Requirements of some test libraries, https://github.com/nunit/docs/wiki/.NET-Core-and-.NET-Standard).

How about `netstandard1.6;netcoreapp2.0;netcoreapp1.0;net45;net35`? Is is suitable?

**Comment by cannorin** [comment]
It means that you can't target netstandard in the test project (in your case, https://github.com/yutopp/VJson/blob/master/VJson.standalone/VJson.Editor.Tests/VJson.Editor.Tests.csproj ). Keep the test project as is and it will work.

**Comment by yutopp** [comment]
Oops, that right. Thanks!

I tried to change the `TargetFrameworks` to

- `VJson.csproj`: `netstandard1.6;net45;net35`
- `VJson.Editor.Tests.csproj`: `netcoreapp2.0;net45;net35`

and it worked well! I didn't notice that csproj can resolve a relation of target frameworks (`netstandard1.6` is a subset of `netcoreapp2.0`).

**Comment by yutopp** [comment]
Merged this changes. Thank you again.
